#!/bin/bash

# Get the Python file name from the environment variable
py_file=$PYFILE

# Check if the environment variable is set
if [ -z "$py_file" ]; then
  echo "Error: The PYFILE environment variable is not set."
  exit 1
fi

# Check if the Python file exists
if [ ! -f "$py_file" ]; then
  echo "Error: Python file '$py_file' not found."
  exit 1
fi

# Run the Python script
python "$py_file"
















